version: "3.8"

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./htpasswd-registry:/etc/htpasswd-registry